### ISSUE TITLE
Non-void function can return without passing value

### ISSUE THREAD

**Issue by alxmjo** [ajscimone/Cpp-Chess-Gui#13]
It's possible for this function to return without passing a bool (if both if conditions are not met). Sorry for not catching this before. Suggested change:

```
bool King::isValidMove(const Board *board, const std::pair<int, int> &fromCoords, const std::pair<int, int> &toCoords) const
{
	if (board->getMoveLength(fromCoords, toCoords) == 1)
	{
		return true;
	}
	else if (!moved && board->isValidCastle(fromCoords, toCoords))
	{
		return true;
	}
	else
	{
		return false;
	}
}
```

https://github.com/ajscimone/Cpp-Chess-Gui/blob/207a7198723b319ea75ec17123d9d5a9066cc34a/source/King.cpp#L22

**Comment by djbauman** [comment]
Suggestion implemented. Thanks for spotting that.
